namespace :db do
  desc "Create sample data"
  task :populate => :environment do
    Rake::Task['db:reset'].invoke
    
    # select 'Person.create!(:first_name => "' + FirstName + '", :last_name => "' + LastName + '")' 
    #   from people
    # 
    # select 'Person.find_by_first_name_and_last_name("' + firstName + '", "' 
    #      + lastName + '").events.create!(:description => "' 
    #      + replace(convert(varchar(200), o.description), '"', '\"') + '", :event_date => "' + convert(varchar(10), o.occasionDate, 121) + '", :gift_ideas => "' + isNull(o.giftIdeas, '') + '")'
    #      --, o.*
    #   from people p
    #   join occasions o
    #     on p.personid = o.personid
    #  where description is not null
    
    Person.create!(:first_name => "Preston", :last_name => "Rohner")
    Person.create!(:first_name => "Tom", :last_name => "Zachary")
    Person.create!(:first_name => "Evelyn", :last_name => "Bettauer")
    Person.create!(:first_name => "Ashley", :last_name => "Rohner")
    Person.create!(:first_name => "Steve", :last_name => "Cote")
    Person.create!(:first_name => "Scott & Suzanne", :last_name => "Silverstein")
    Person.create!(:first_name => "Aaron", :last_name => "Leckinger")
    Person.create!(:first_name => "James", :last_name => "Carr")
    Person.create!(:first_name => "Ron", :last_name => "Rohner")
    Person.create!(:first_name => "Bill", :last_name => "Ramos")
    Person.create!(:first_name => "Frank", :last_name => "Minitello")
    Person.create!(:first_name => "Mike", :last_name => "Shriver")
    Person.create!(:first_name => "Anne", :last_name => "Tokes")
    Person.create!(:first_name => "Gary", :last_name => "Abrams")
    Person.create!(:first_name => "Donna", :last_name => "Jones")
    Person.create!(:first_name => "Nannette", :last_name => "Kyer")
    Person.create!(:first_name => "Mark", :last_name => "Leekley")
    Person.create!(:first_name => "Chris & Moira", :last_name => "Marshall")
    Person.create!(:first_name => "Bill & Irene", :last_name => "Nash")
    Person.create!(:first_name => "Nancy", :last_name => "Noonan")
    Person.create!(:first_name => "Kristin", :last_name => "Riley")
    Person.create!(:first_name => "Gino", :last_name => "Spinelli")
    Person.create!(:first_name => "Tres", :last_name => "Smith")
    Person.create!(:first_name => "Lisa & Erik", :last_name => "Nelson")
    Person.create!(:first_name => "Bob", :last_name => "Syphers")
    Person.create!(:first_name => "Mike", :last_name => "Moran")
    Person.create!(:first_name => "Marko", :last_name => "Nadberezny")
    Person.create!(:first_name => "Andrea", :last_name => "Breuer")
    Person.create!(:first_name => "Maud", :last_name => "Keisman")
    Person.create!(:first_name => "Pat", :last_name => "Kennedy")
    Person.create!(:first_name => "Bart", :last_name => "Matthews")
    Person.create!(:first_name => "Abe", :last_name => "Schryer")
    Person.create!(:first_name => "Sy & Naomi", :last_name => "Tomashoff")
    Person.create!(:first_name => "Maggie & Tom", :last_name => "Keisman")
    Person.create!(:first_name => "Eleanor", :last_name => "Weston")
    Person.create!(:first_name => "Ivy", :last_name => "Tomashoff")
    Person.create!(:first_name => "Guy", :last_name => "Lundberg")
    Person.create!(:first_name => "Chance", :last_name => "Hutchison")
    Person.create!(:first_name => "Ihor", :last_name => "Nadberezny")
    Person.create!(:first_name => "Nina", :last_name => "Milus")
    Person.create!(:first_name => "Dennis", :last_name => "McMasters")
    Person.create!(:first_name => "Jose", :last_name => "Hernandez")
    Person.create!(:first_name => "Chad", :last_name => "Lowd")
    Person.create!(:first_name => "Andre", :last_name => "Monostori")
    Person.create!(:first_name => "Jennifer", :last_name => "Hayday")
    Person.create!(:first_name => "Dean", :last_name => "Chafee")
    Person.create!(:first_name => "Jon", :last_name => "Yates")
    Person.create!(:first_name => "Nand", :last_name => "Hart-Nibbrig")
    Person.create!(:first_name => "Kate", :last_name => "Dudley")
    Person.create!(:first_name => "Aaron", :last_name => "Mestman")
    Person.create!(:first_name => "Carla", :last_name => "McNellis")
    Person.create!(:first_name => "Ed", :last_name => "Ericson")
    Person.create!(:first_name => "Fanny", :last_name => "Paul")
    Person.create!(:first_name => "Elizabeth", :last_name => "Judkins")
    Person.create!(:first_name => "Jordana", :last_name => "Glasser")
    Person.create!(:first_name => "Hope", :last_name => "Faulkner")
    Person.create!(:first_name => "Patricia", :last_name => "Lim")
    Person.create!(:first_name => "Bert", :last_name => "(massage)")
    Person.create!(:first_name => "Dick", :last_name => "Sutherland")
    Person.create!(:first_name => "@ngelique", :last_name => "Davis")
    Person.create!(:first_name => "Harvey", :last_name => "Elrich")
    Person.create!(:first_name => "George", :last_name => "Davancens")
    Person.create!(:first_name => "Chuck", :last_name => "Babler")
    Person.create!(:first_name => "Trish", :last_name => "Tapp")
    Person.create!(:first_name => "Debbie", :last_name => "Schaub")
    Person.create!(:first_name => "Daniel", :last_name => "James")
    Person.create!(:first_name => "John ", :last_name => "Parsons")
    Person.create!(:first_name => "Cinnamon", :last_name => "Lizarzaburu")
    Person.create!(:first_name => "Alexis", :last_name => "Foy")
    Person.create!(:first_name => "Denise", :last_name => "Dalven")
    Person.create!(:first_name => "Matt", :last_name => "Wardle")
    Person.create!(:first_name => "Troy", :last_name => "Kachurka")
    Person.create!(:first_name => "Tom ", :last_name => "Roberts")
    Person.create!(:first_name => "Amanda", :last_name => "Nelson")
    Person.create!(:first_name => "Steve ", :last_name => "Neuschotz")
    Person.create!(:first_name => "Tom", :last_name => "Lenk")
    Person.create!(:first_name => "Navin ", :last_name => "Kistan")
    Person.create!(:first_name => "John", :last_name => "Patterson")
    Person.create!(:first_name => "Melissa", :last_name => "Black")
    Person.create!(:first_name => "Dave", :last_name => "Ross")
    Person.create!(:first_name => "Colleen", :last_name => "Thorndike")
    Person.create!(:first_name => "Chris", :last_name => "Lego")
    Person.create!(:first_name => "Traci", :last_name => "Treffert")
    Person.create!(:first_name => "Dominic", :last_name => "Tondino")
    Person.create!(:first_name => "Lee", :last_name => "Washington")
    Person.create!(:first_name => "Kevin", :last_name => "Blayne")
    Person.create!(:first_name => "Jay", :last_name => "Dizon")
    Person.create!(:first_name => "Steve", :last_name => "Conyers")
    Person.create!(:first_name => "Mike", :last_name => "Jay")
    Person.create!(:first_name => "Jun", :last_name => "Tecson")
    Person.create!(:first_name => "Yves", :last_name => "Accad")
    Person.create!(:first_name => "Brandon", :last_name => "Hack")
    Person.create!(:first_name => "Skee ", :last_name => "Goedhart")
    Person.create!(:first_name => "Dave", :last_name => "Fallon")
    Person.create!(:first_name => "Ron", :last_name => "Moskowitz")
    Person.create!(:first_name => "Deb", :last_name => "Stewart")
    Person.create!(:first_name => "Mo", :last_name => "Danesh")

    Person.find_by_first_name_and_last_name("Preston", "Rohner").events.create!(:description => "Liz's birthday", :event_date => "1966-10-03", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Tom", "Zachary").events.create!(:description => "Tom's birthday", :event_date => "1957-07-19", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Evelyn", "Bettauer").events.create!(:description => "Mom's birthday", :event_date => "1937-01-30", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Evelyn", "Bettauer").events.create!(:description => "Jack's birthday", :event_date => "2027-05-13", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Ashley", "Rohner").events.create!(:description => "Ashley's birthday", :event_date => "1970-11-09", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Steve", "Cote").events.create!(:description => "Steve's birthday", :event_date => "1967-09-05", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Scott & Suzanne", "Silverstein").events.create!(:description => "Expected C-section", :event_date => "1999-09-09", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Aaron", "Leckinger").events.create!(:description => "Liam's birthday", :event_date => "1997-09-02", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Aaron", "Leckinger").events.create!(:description => "Lars's birthday", :event_date => "1999-12-03", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("James", "Carr").events.create!(:description => "James' birthday", :event_date => "1952-08-30", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Evelyn", "Bettauer").events.create!(:description => "Their anniversary", :event_date => "1987-02-15", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Preston", "Rohner").events.create!(:description => "Sam's birthday", :event_date => "1996-12-11", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Ron", "Rohner").events.create!(:description => "Dad's birthday", :event_date => "1935-04-17", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Ron", "Rohner").events.create!(:description => "Nancy's birthday", :event_date => "1942-03-21", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Bill", "Ramos").events.create!(:description => "Bill's birthday", :event_date => "1999-09-27", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Frank", "Minitello").events.create!(:description => "Frank's birthday", :event_date => "1973-05-06", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Mike", "Shriver").events.create!(:description => "Mike and Shannon's anniversary", :event_date => "1999-10-02", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Anne", "Tokes").events.create!(:description => "Anne's birthday", :event_date => "1967-11-15", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Gary", "Abrams").events.create!(:description => "Gary's birthday (year is questionable)", :event_date => "1963-09-08", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Gary", "Abrams").events.create!(:description => "Brian's birthday", :event_date => "1991-05-02", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Donna", "Jones").events.create!(:description => "Sean (son's) birthday", :event_date => "1998-09-13", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Nannette", "Kyer").events.create!(:description => "Hannah's birthday", :event_date => "1993-12-10", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Nannette", "Kyer").events.create!(:description => "Bram's birthday", :event_date => "1996-07-10", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Mark", "Leekley").events.create!(:description => "Lauren's birthday (day is questionable)", :event_date => "1995-05-27", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Chris & Moira", "Marshall").events.create!(:description => "Chris's birthday (year is questionable)", :event_date => "1963-10-07", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Chris & Moira", "Marshall").events.create!(:description => "Moira's birthday (year is questionable)", :event_date => "1967-07-28", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Bill & Irene", "Nash").events.create!(:description => "Billy's birthday", :event_date => "1967-07-07", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Nancy", "Noonan").events.create!(:description => "Wedding anniversary with John", :event_date => "1996-07-05", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Kristin", "Riley").events.create!(:description => "Cullen Theodore's birthday", :event_date => "1996-02-05", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Kristin", "Riley").events.create!(:description => "Kevin Alexander & Eion Patrick's b-days", :event_date => "1997-06-03", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Gino", "Spinelli").events.create!(:description => "Anniversary", :event_date => "1990-12-29", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Tom", "Zachary").events.create!(:description => "Ryan's birthday (approximate)", :event_date => "1991-05-14", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Chris & Moira", "Marshall").events.create!(:description => "Liam's birthday", :event_date => "1997-10-07", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Tres", "Smith").events.create!(:description => "Anniversary", :event_date => "1981-10-10", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Mike", "Shriver").events.create!(:description => "Shannon's birthday", :event_date => "1966-10-15", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Nannette", "Kyer").events.create!(:description => "Nan's birthday", :event_date => "1967-06-30", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Lisa & Erik", "Nelson").events.create!(:description => "Emma Elizabeth's birthday", :event_date => "1999-10-26", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("James", "Carr").events.create!(:description => "Sam's birthday", :event_date => "1984-03-23", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("James", "Carr").events.create!(:description => "Jonathan's birthday", :event_date => "1981-12-07", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("James", "Carr").events.create!(:description => "Laura's birthday", :event_date => "1953-06-08", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("James", "Carr").events.create!(:description => "Hanna's birthday", :event_date => "1987-05-29", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("James", "Carr").events.create!(:description => "Rebekah's birthday", :event_date => "1979-04-19", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Gino", "Spinelli").events.create!(:description => "Lauren's birthday", :event_date => "1962-01-04", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Bob", "Syphers").events.create!(:description => "Bob's birthday", :event_date => "1947-02-09", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Bill & Irene", "Nash").events.create!(:description => "Austin Leonard & Brandon William", :event_date => "2000-01-23", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Mike", "Moran").events.create!(:description => "Josh's due date", :event_date => "2000-02-26", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Preston", "Rohner").events.create!(:description => "Our anniversary", :event_date => "2005-02-26", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Preston", "Rohner").events.create!(:description => "Valentine's Day", :event_date => "2000-02-14", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Mike", "Moran").events.create!(:description => "Ruth's birthday", :event_date => "1995-08-11", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Marko", "Nadberezny").events.create!(:description => "Marko's birthday", :event_date => "1966-03-18", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Andrea", "Breuer").events.create!(:description => "Ted's birthday (year questionable)", :event_date => "1964-03-21", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Andrea", "Breuer").events.create!(:description => "Julia's birthday", :event_date => "1995-10-04", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("James", "Carr").events.create!(:description => "James' Anniversary", :event_date => "1978-04-28", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Donna", "Jones").events.create!(:description => "Donna's birthday", :event_date => "1963-04-11", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Maud", "Keisman").events.create!(:description => "Maud's birthday (year questionable)", :event_date => "1963-04-08", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Pat", "Kennedy").events.create!(:description => "Pat's anniversary", :event_date => "1988-07-30", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Bart", "Matthews").events.create!(:description => "Bart's birthday", :event_date => "1968-09-28", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Ron", "Rohner").events.create!(:description => "Their anniversary (year questionable)", :event_date => "1986-06-09", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Abe", "Schryer").events.create!(:description => "Abe's birthday", :event_date => "1965-05-30", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Sy & Naomi", "Tomashoff").events.create!(:description => "Naomi's birthday (year?)", :event_date => "1927-05-13", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Sy & Naomi", "Tomashoff").events.create!(:description => "Sy's birthday (year?)", :event_date => "1922-09-11", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Sy & Naomi", "Tomashoff").events.create!(:description => "Their anniversary", :event_date => "1952-05-25", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Lisa & Erik", "Nelson").events.create!(:description => "Lisa's birthday", :event_date => "1965-11-01", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Maggie & Tom", "Keisman").events.create!(:description => "Olivia Sophie Allen's birthday", :event_date => "1996-05-07", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Eleanor", "Weston").events.create!(:description => "Eleanor's birthday", :event_date => "1940-04-19", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Gino", "Spinelli").events.create!(:description => "Gino's birthday", :event_date => "1964-05-20", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Ivy", "Tomashoff").events.create!(:description => "Ivy's birthday", :event_date => "1956-06-15", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Guy", "Lundberg").events.create!(:description => "David's birthday", :event_date => "1986-05-24", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Chance", "Hutchison").events.create!(:description => "Chance's birthday", :event_date => "1967-06-30", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Ihor", "Nadberezny").events.create!(:description => "Ihor's birthday", :event_date => "1967-08-05", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Nina", "Milus").events.create!(:description => "Nina's birthday", :event_date => "2000-02-22", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Dennis", "McMasters").events.create!(:description => "Shecky's birthday", :event_date => "1961-08-07", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jose", "Hernandez").events.create!(:description => "Jose's birthday", :event_date => "1965-08-24", :gift_ideas => "Photo of sailor/nurse after WWII")
    Person.find_by_first_name_and_last_name("Andrea", "Breuer").events.create!(:description => "Andrea's birthday", :event_date => "1966-08-21", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Chad", "Lowd").events.create!(:description => "Chad's birthday", :event_date => "1966-08-12", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Mike", "Moran").events.create!(:description => "Mike's birthday", :event_date => "1964-02-24", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Andre", "Monostori").events.create!(:description => "Jamie's birthday", :event_date => "1978-08-22", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Andre", "Monostori").events.create!(:description => "Andre's birthday", :event_date => "1971-08-29", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Andre", "Monostori").events.create!(:description => "Jamie's dad's birthday", :event_date => "2000-08-18", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Andre", "Monostori").events.create!(:description => "Andre's mom's birthday", :event_date => "2000-08-19", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jennifer", "Hayday").events.create!(:description => "Jennifer's birthday", :event_date => "1966-04-17", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jennifer", "Hayday").events.create!(:description => "Felicia's birthday?", :event_date => "2000-03-22", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Sy & Naomi", "Tomashoff").events.create!(:description => "Joel's birthday", :event_date => "1954-08-26", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Sy & Naomi", "Tomashoff").events.create!(:description => "Joel's death", :event_date => "1989-09-25", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Gino", "Spinelli").events.create!(:description => "Nico's birthday", :event_date => "2000-09-04", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Dean", "Chafee").events.create!(:description => "Dean's birthday", :event_date => "1963-08-04", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Dean", "Chafee").events.create!(:description => "Their anniversary", :event_date => "1997-06-27", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Aaron", "Leckinger").events.create!(:description => "Aaron's birthday", :event_date => "1968-09-25", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Chris & Moira", "Marshall").events.create!(:description => "Erin Marie's birthday", :event_date => "2001-03-19", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Aaron", "Leckinger").events.create!(:description => "Hayley's birthday", :event_date => "1986-12-14", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jon", "Yates").events.create!(:description => "Becky's birthday?", :event_date => "2000-10-28", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Nand", "Hart-Nibbrig").events.create!(:description => "Nand's birthday?", :event_date => "2000-10-29", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Kate", "Dudley").events.create!(:description => "Kate's birthday", :event_date => "2000-12-24", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Carla", "McNellis").events.create!(:description => "Carla's birthday", :event_date => "1964-03-19", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jon", "Yates").events.create!(:description => "Jon's birthday, year questionable", :event_date => "1957-04-12", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Tom", "Zachary").events.create!(:description => "Mirinda's birthday", :event_date => "2001-04-10", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Ed", "Ericson").events.create!(:description => "Ed's birthday", :event_date => "1965-07-23", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Fanny", "Paul").events.create!(:description => "Fanny's birthday", :event_date => "1928-03-08", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Elizabeth", "Judkins").events.create!(:description => "Elizabeth's birthday", :event_date => "1949-10-31", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jordana", "Glasser").events.create!(:description => "Jordana's birthday", :event_date => "1965-01-04", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jordana", "Glasser").events.create!(:description => "Jordana's AA birthday", :event_date => "1995-10-06", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Hope", "Faulkner").events.create!(:description => "Hope's birthday", :event_date => "1953-03-20", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Patricia", "Lim").events.create!(:description => "Ben's birthday", :event_date => "2001-04-05", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Patricia", "Lim").events.create!(:description => "Patricia's birthday", :event_date => "2001-04-08", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Patricia", "Lim").events.create!(:description => "Patricia's wedding", :event_date => "2002-04-07", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Gino", "Spinelli").events.create!(:description => "Kierstyn's birthday", :event_date => "1995-04-08", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Guy", "Lundberg").events.create!(:description => "Guy died", :event_date => "2000-12-24", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Bert", "(massage)").events.create!(:description => "Bert's birthday", :event_date => "1943-06-06", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Aaron", "Leckinger").events.create!(:description => "Eli Liev's birthday", :event_date => "2001-06-09", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Dick", "Sutherland").events.create!(:description => "Dick's birthday", :event_date => "2001-06-27", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("@ngelique", "Davis").events.create!(:description => "@ngelique's birthday", :event_date => "1968-07-12", :gift_ideas => "Send a real card")
    Person.find_by_first_name_and_last_name("Harvey", "Elrich").events.create!(:description => "Harvey's birthday", :event_date => "1922-07-09", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Harvey", "Elrich").events.create!(:description => "Harvey died", :event_date => "2001-10-20", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jennifer", "Hayday").events.create!(:description => "Paige's birthday", :event_date => "1992-07-12", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Nina", "Milus").events.create!(:description => "Nina's wedding", :event_date => "2001-07-28", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Fanny", "Paul").events.create!(:description => "Fanny's \"name day\"", :event_date => "2002-01-06", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Frank", "Minitello").events.create!(:description => "Frank & Shannon getting married", :event_date => "2002-08-31", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("George", "Davancens").events.create!(:description => "George's birthday", :event_date => "1962-01-30", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("@ngelique", "Davis").events.create!(:description => "Indy's birthday", :event_date => "2001-03-31", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("@ngelique", "Davis").events.create!(:description => "Danique's birthday", :event_date => "1998-08-28", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Ihor", "Nadberezny").events.create!(:description => "Their anniversary", :event_date => "2009-06-13", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Anne", "Tokes").events.create!(:description => "Rudy's birthday", :event_date => "2002-03-14", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Anne", "Tokes").events.create!(:description => "Adam's birthday (year is questionable)", :event_date => "1970-04-04", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jose", "Hernandez").events.create!(:description => "Becky's birthday", :event_date => "1972-04-14", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jennifer", "Hayday").events.create!(:description => "Sarah's birthday", :event_date => "2002-05-04", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Chuck", "Babler").events.create!(:description => "Lisa's birthday", :event_date => "2002-04-30", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Trish", "Tapp").events.create!(:description => "Trish's birthday", :event_date => "1968-02-17", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jennifer", "Hayday").events.create!(:description => "Her mom's birthday", :event_date => "1937-05-13", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Aaron", "Leckinger").events.create!(:description => "Lori's birthday", :event_date => "1962-09-08", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jennifer", "Hayday").events.create!(:description => "Her father passed", :event_date => "2001-06-21", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Patricia", "Lim").events.create!(:description => "Patricia's baby is due", :event_date => "2003-01-07", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Debbie", "Schaub").events.create!(:description => "Debbie's birthday", :event_date => "1962-10-28", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Daniel", "James").events.create!(:description => "Daniel's birthday", :event_date => "1984-09-08", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("John ", "Parsons").events.create!(:description => "John's son's birthday", :event_date => "2001-09-13", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("John ", "Parsons").events.create!(:description => "John running NYC Marathon", :event_date => "2002-11-03", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jennifer", "Hayday").events.create!(:description => "Patrick's birthday", :event_date => "2002-09-19", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jennifer", "Hayday").events.create!(:description => "Patrick died", :event_date => "1994-09-02", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jennifer", "Hayday").events.create!(:description => "Henry Alexander Boyle (Sarah's) born", :event_date => "2002-09-27", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Cinnamon", "Lizarzaburu").events.create!(:description => "Cinnamon's birthday", :event_date => "1976-05-12", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Cinnamon", "Lizarzaburu").events.create!(:description => "Greg's birthday", :event_date => "1969-03-07", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Chuck", "Babler").events.create!(:description => "Chuck died", :event_date => "2003-01-11", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Carla", "McNellis").events.create!(:description => "Carla's AA birthday", :event_date => "1986-03-10", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Ihor", "Nadberezny").events.create!(:description => "Nicole's birthday", :event_date => "1973-04-18", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Alexis", "Foy").events.create!(:description => "Alexis's birthday", :event_date => "1967-04-27", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Denise", "Dalven").events.create!(:description => "Denise's & Rick's birthday", :event_date => "2003-04-21", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Matt", "Wardle").events.create!(:description => "Matt's wedding anniv.", :event_date => "1997-05-31", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Matt", "Wardle").events.create!(:description => "Matt's birthday", :event_date => "2003-07-18", :gift_ideas => "peanuts/bacon")
    Person.find_by_first_name_and_last_name("Troy", "Kachurka").events.create!(:description => "Troy's son's birthday", :event_date => "2003-07-18", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Guy", "Lundberg").events.create!(:description => "Becky's birthday", :event_date => "1950-08-02", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Guy", "Lundberg").events.create!(:description => "Victoria's birthday", :event_date => "1991-10-14", :gift_ideas => "horseback riding ")
    Person.find_by_first_name_and_last_name("Tom ", "Roberts").events.create!(:description => "Tom's birthday", :event_date => "2003-01-08", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Amanda", "Nelson").events.create!(:description => "Amanda's birthday", :event_date => "2003-09-16", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Alexis", "Foy").events.create!(:description => "George's birthday", :event_date => "1936-10-18", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Steve ", "Neuschotz").events.create!(:description => "Shawnna's birthday", :event_date => "2004-04-07", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Steve ", "Neuschotz").events.create!(:description => "Noah's birthday", :event_date => "1999-04-18", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Tom", "Lenk").events.create!(:description => "Lisa's birthday", :event_date => "2004-02-24", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Preston", "Rohner").events.create!(:description => "First date w/ Alexis", :event_date => "2003-03-04", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jennifer", "Hayday").events.create!(:description => "Isabelle's birthday (Flea's daughter)", :event_date => "1994-05-25", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Navin ", "Kistan").events.create!(:description => "Damisha's birthday", :event_date => "2004-04-28", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Navin ", "Kistan").events.create!(:description => "Sammy's birthday", :event_date => "1996-09-01", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Steve ", "Neuschotz").events.create!(:description => "Meredith Lee's birthday", :event_date => "2004-09-15", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Tom", "Zachary").events.create!(:description => "Wedding anniversary", :event_date => "2002-06-09", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("John", "Patterson").events.create!(:description => "John's birthday", :event_date => "1967-08-01", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Melissa", "Black").events.create!(:description => "Melissa's birthday", :event_date => "1954-10-16", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Dave", "Ross").events.create!(:description => "Marley's birthday", :event_date => "2000-06-21", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Colleen", "Thorndike").events.create!(:description => "Abby's birthday", :event_date => "2001-09-15", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Alexis", "Foy").events.create!(:description => "Vicki's birthday", :event_date => "1946-10-24", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Chris", "Lego").events.create!(:description => "Chris's birthday", :event_date => "1976-02-13", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Colleen", "Thorndike").events.create!(:description => "Ryan's birthday", :event_date => "2005-01-13", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Cinnamon", "Lizarzaburu").events.create!(:description => "Gabrielle's birthday", :event_date => "2005-08-25", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Traci", "Treffert").events.create!(:description => "Traci's birthday", :event_date => "2007-01-08", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Dominic", "Tondino").events.create!(:description => "Dominic's birthday", :event_date => "1967-05-23", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Colleen", "Thorndike").events.create!(:description => "Colleen's birthday", :event_date => "1972-05-01", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Tom", "Zachary").events.create!(:description => "Paige Amelia's birthday", :event_date => "2007-08-29", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Preston", "Rohner").events.create!(:description => "Chase, Cole & Genevieve", :event_date => "2008-01-17", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Lee", "Washington").events.create!(:description => "Lee & Leanne's Anniversary", :event_date => "1998-01-21", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Lee", "Washington").events.create!(:description => "Kianna's birthday", :event_date => "1996-05-07", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Kevin", "Blayne").events.create!(:description => "Kevin's birthday", :event_date => "1965-04-05", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Preston", "Rohner").events.create!(:description => "Genevieve came home", :event_date => "2008-03-03", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Preston", "Rohner").events.create!(:description => "Chase came home", :event_date => "2008-03-06", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jay", "Dizon").events.create!(:description => "Jay's birthday", :event_date => "1978-09-15", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Steve", "Conyers").events.create!(:description => "Steve's birthday", :event_date => "1951-10-27", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Preston", "Rohner").events.create!(:description => "Cole came home (correct date?)", :event_date => "2008-04-08", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Mike", "Jay").events.create!(:description => "Mike's anniversary", :event_date => "1976-09-15", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Kevin", "Blayne").events.create!(:description => "Lily's birthday", :event_date => "2008-09-23", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Preston", "Rohner").events.create!(:description => "National Talk Like a Pirate Day", :event_date => "2010-09-19", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jun", "Tecson").events.create!(:description => "Jun's birthday", :event_date => "1966-02-03", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Jun", "Tecson").events.create!(:description => "Megan's birthday", :event_date => "2004-05-28", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Yves", "Accad").events.create!(:description => "The Deuce's birthday", :event_date => "2010-06-08", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Lee", "Washington").events.create!(:description => "Lee's birthday (year questionable)", :event_date => "1968-02-20", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Brandon", "Hack").events.create!(:description => "Mason's birthday", :event_date => "2010-11-28", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Skee ", "Goedhart").events.create!(:description => "Julia's birthday", :event_date => "2009-07-09", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Yves", "Accad").events.create!(:description => "Yves's birthday", :event_date => "2012-05-08", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Dave", "Fallon").events.create!(:description => "Dave's birthday", :event_date => "1978-10-07", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Ron", "Moskowitz").events.create!(:description => "Ron's birthday", :event_date => "1969-11-03", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Deb", "Stewart").events.create!(:description => "Deb's birthday", :event_date => "2014-01-16", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Mo", "Danesh").events.create!(:description => "Mo's birthday", :event_date => "1959-12-17", :gift_ideas => "")
    Person.find_by_first_name_and_last_name("Alexis", "Foy").events.create!(:description => "Paula's birthday", :event_date => "2013-12-14", :gift_ideas => "")    
  end
end